plugins:
  events_add_to_calendar:
    client: true
    default: false
  events_event_label_icon:
    client: true
    default: 'calendar'
  events_event_label_format:
    client: true
    default: 'MMMM Do, HH:mm'
  events_event_label_short_format:
    client: true
    default: 'M-D, HH:mm'
